# 独立配置文件，可以拿到jar外面跑
spring:
  application:
    name: yf-exam-lite
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yf_exam?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    filters: stat
    max-active: 5000
    initial-size: 20
    max-wait: 6000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 1000
    async-init: true

server:
  port: 8101
  # 启用服务端压缩
  compression:
    enabled: true
    min-response-size: 10
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

# 文件上传配置
conf:
  upload:
    # 物理文件存储位置，以/结束，windows已正斜杠，如：d:/exam-upload/
    dir: /data/upload/
    # 访问地址，注意不要去除/upload/file/，此节点为虚拟标识符
    # 如：http://localhost:8101/upload/file/exam.jpg，对应物理文件为：/data/upload/exam.jpg
    url: http://localhost:8101/upload/file/

# 开启文档
swagger:
  enable: true

logging:
  level:
    root: debug
  path: logs/${spring.application.name}/
